//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargobooking
    {
        public int Id { get; set; }
        public string datecreated { get; set; }
        public Nullable<double> itemweight { get; set; }
        public Nullable<int> user_id { get; set; }
        public string status { get; set; }
        public Nullable<int> schedule_id { get; set; }
    }
}
