//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerInfo
    {
        public int info_id { get; set; }
        public Nullable<int> groupnumber { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string middle { get; set; }
        public Nullable<int> age { get; set; }
        public string passengertype { get; set; }
        public Nullable<bool> isEnsured { get; set; }
        public Nullable<bool> isVaxxed { get; set; }
    }
}
