//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int schedule_id { get; set; }
        public string transport_name { get; set; }
        public string departuretime { get; set; }
        public string arrivaltime { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<double> priceregular { get; set; }
        public Nullable<double> pricetourist { get; set; }
        public Nullable<double> pricebusiness { get; set; }
        public Nullable<double> pricebusiness2 { get; set; }
        public string sched_status { get; set; }
        public Nullable<int> booklimit { get; set; }
    }
}
