//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport
    {
        public int transport_id { get; set; }
        public string transport_name { get; set; }
        public string transport_type { get; set; }
        public string transport_status { get; set; }
    }
}
